version: '3.9'
services:
  nginx-tunnel:
    image: nginx:1.21.6-alpine
    hostname: nginx
    container_name: nginx-tunnel
    volumes:
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - $PWD/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - metanet1
    ports:
      - 9090:80
    cpus: 1
    mem_limit: 128m
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  metanet1:
    driver: bridge
